# Generated by Django 4.1.7 on 2023-02-19 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priority', models.IntegerField(choices=[(0, 'Baixa'), (1, 'Media'), (2, 'Alta')], db_index=True, default=1)),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Andamento'), (2, 'Concluido')], db_index=True, default=0)),
                ('event_at', models.DateTimeField(db_index=True)),
                ('finish_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
