# Generated by Django 4.1.7 on 2023-02-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapi', '0003_alter_task_finish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Baixa'), (1, 'Media'), (2, 'Alta')], db_index=True, default=1),
        ),
    ]
