name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - shell: bash
      env:
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      run: "$DATABASE_HOST"
