name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      run: docker build . --build-arg DATABASE_HOST=${{ secrets.DATABASE_HOST }} --build-arg DATABASE_USER=${{ secrets.DATABASE_USER }} --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
