name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        tasks_secrets: ${{ secrets.tasks_secrets }}
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
